### ISSUE TITLE
Cannot use on MediaWiki 1.41

### ISSUE THREAD

**Issue by jdlrobson** [immewnity/mediawiki-fluent#13]
Hi there I tried to use the skin on MediaWiki 1.41 (for https://skins-demo.wmflabs.org/) but got the following error. Let me know if you need any further information!

```
Deprecated: Use of QuickTemplate::(get/html/text/haveData) with parameter `headelement` was deprecated in MediaWiki 1.39. [Called from QuickTemplate::get in /vagrant/mediawiki/includes/skins/QuickTemplate.php at line 145] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 378
MediaWiki internal error.

Original exception: [ec864ae15cfcbdcf7955b5f4] /wiki/Special:Version?useskin=fluent Error: Call to undefined method LanguageEn::convert()
Backtrace:
from /vagrant/mediawiki/skins/mediawiki-Fluent/Fluent/includes/FluentTemplate.php(131)
#0 /vagrant/mediawiki/skins/mediawiki-Fluent/Fluent/includes/FluentTemplate.php(15): FluentTemplate->getLogo()
#1 /vagrant/mediawiki/includes/skins/SkinTemplate.php(148): FluentTemplate->execute()
#2 /vagrant/mediawiki/includes/skins/SkinTemplate.php(174): SkinTemplate->generateHTML()
#3 /vagrant/mediawiki/includes/Output/OutputPage.php(3054): SkinTemplate->outputPage()
#4 /vagrant/mediawiki/includes/actions/ActionEntryPoint.php(168): MediaWiki\Output\OutputPage->output()
#5 /vagrant/mediawiki/includes/MediaWikiEntryPoint.php(159): MediaWiki\Actions\ActionEntryPoint->execute()
#6 /vagrant/mediawiki/index.php(50): MediaWiki\MediaWikiEntryPoint->run()
#7 /var/www/w/index.php(5): require(string)
#8 {main}

Exception caught inside exception handler: [ec864ae15cfcbdcf7955b5f4] /wiki/Special:Version?useskin=fluent Error: Call to undefined method LanguageEn::convert()
Backtrace:
from /vagrant/mediawiki/skins/mediawiki-Fluent/Fluent/includes/FluentTemplate.php(131)
#0 /vagrant/mediawiki/skins/mediawiki-Fluent/Fluent/includes/FluentTemplate.php(15): FluentTemplate->getLogo()
#1 /vagrant/mediawiki/includes/skins/SkinTemplate.php(148): FluentTemplate->execute()
#2 /vagrant/mediawiki/includes/skins/SkinTemplate.php(174): SkinTemplate->generateHTML()
#3 /vagrant/mediawiki/includes/Output/OutputPage.php(3054): SkinTemplate->outputPage()
#4 /vagrant/mediawiki/includes/exception/MWExceptionRenderer.php(188): MediaWiki\Output\OutputPage->output()
#5 /vagrant/mediawiki/includes/exception/MWExceptionRenderer.php(105): MWExceptionRenderer::reportHTML()
#6 /vagrant/mediawiki/includes/exception/MWExceptionHandler.php(133): MWExceptionRenderer::output()
#7 /vagrant/mediawiki/includes/exception/MWExceptionHandler.php(237): MWExceptionHandler::report()
#8 /vagrant/mediawiki/includes/MediaWikiEntryPoint.php(180): MWExceptionHandler::handleException()
#9 /vagrant/mediawiki/includes/actions/ActionEntryPoint.php(87): MediaWiki\MediaWikiEntryPoint->handleTopLevelError()
#10 /vagrant/mediawiki/includes/MediaWikiEntryPoint.php(164): MediaWiki\Actions\ActionEntryPoint->handleTopLevelError()
#11 /vagrant/mediawiki/index.php(50): MediaWiki\MediaWikiEntryPoint->run()
#12 /var/www/w/index.php(5): require(string)
#13 {main}
```

**Comment by immewnity** [comment]
Ach, yet another breaking bug that came right over from the 1.35 Example skin (https://github.com/wikimedia/mediawiki-skins-Example/blob/3f0fe422a20723858145cda1cdb415960b0daa90/includes/ExampleTemplate.php#L112C74-L112C75), which was rewritten so heavily for 1.36-on that it's hardly even the same skin (this file no longer exists) - so looking upstream isn't an option here. Will try to see if any other 1.35 Example-based skins found a solution... else this looks like it'll have to wait until #1 .

**Comment by immewnity** [comment]
Looks like https://gerrit.wikimedia.org/r/c/mediawiki/core/+/936685 was what caused this
