### ISSUE TITLE
Call to undefined method FluentTemplate::getAfterPortlet()

### ISSUE THREAD

**Issue by redbluegreenhat** [immewnity/mediawiki-fluent#19]
While working on #18 I came across this.

```
MediaWiki internal error.

Original exception: [f5dbe039839fa9206717ba88] /mediawiki/mediawiki-1.41.0/index.php/Special:Preferences Error: Call to undefined method FluentTemplate::getAfterPortlet()
Backtrace:
from /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/skins/Fluent/includes/FluentTemplate.php(555)
#0 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/skins/Fluent/includes/FluentTemplate.php(366): FluentTemplate->getPortlet()
#1 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/skins/Fluent/includes/FluentTemplate.php(41): FluentTemplate->getUserLinks()
#2 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/skins/SkinTemplate.php(148): FluentTemplate->execute()
#3 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/skins/SkinTemplate.php(174): SkinTemplate->generateHTML()
#4 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/Output/OutputPage.php(2947): SkinTemplate->outputPage()
#5 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/MediaWiki.php(978): MediaWiki\Output\OutputPage->output()
#6 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/MediaWiki.php(613): MediaWiki->main()
#7 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/index.php(50): MediaWiki->run()
#8 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/index.php(46): wfIndexMain()
#9 {main}

Exception caught inside exception handler: [f5dbe039839fa9206717ba88] /mediawiki/mediawiki-1.41.0/index.php/Special:Preferences Error: Call to undefined method FluentTemplate::getAfterPortlet()
Backtrace:
from /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/skins/Fluent/includes/FluentTemplate.php(555)
#0 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/skins/Fluent/includes/FluentTemplate.php(366): FluentTemplate->getPortlet()
#1 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/skins/Fluent/includes/FluentTemplate.php(41): FluentTemplate->getUserLinks()
#2 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/skins/SkinTemplate.php(148): FluentTemplate->execute()
#3 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/skins/SkinTemplate.php(174): SkinTemplate->generateHTML()
#4 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/Output/OutputPage.php(2947): SkinTemplate->outputPage()
#5 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/exception/MWExceptionRenderer.php(188): MediaWiki\Output\OutputPage->output()
#6 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/exception/MWExceptionRenderer.php(105): MWExceptionRenderer::reportHTML()
#7 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/exception/MWExceptionHandler.php(134): MWExceptionRenderer::output()
#8 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/exception/MWExceptionHandler.php(251): MWExceptionHandler::report()
#9 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/includes/MediaWiki.php(635): MWExceptionHandler::handleException()
#10 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/index.php(50): MediaWiki->run()
#11 /var/www/localhost/htdocs/mediawiki/mediawiki-1.41.0/index.php(46): wfIndexMain()
#12 {main}
```

**Comment by originalauthority** [comment]
#20
